name: Add To Builders Club
on:
  pull_request:
    branches: [ main, dev ]
    types: [closed]
jobs:
  invite:
    runs-on: ubuntu-latest
    steps:
      - name: Ruhroh
        runs: console.dir(github.event)
      - name: Invite contributor to the organization
        uses: lekterable/inclusive-organization-action@v1.1.0
        with:
          organization: builders-club
          team: contributors
        env:
          ACCESS_TOKEN: ${{ secrets.ORG_ADMIN_ACCESS_TOKEN }}
