name: CD

on:
  push:
    branches: [ main ]

jobs:
  bump:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - uses: tool3/bump@v1
        id: bump
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user: 'Versioning Action'
          email: 'versioning@github.com'
          branch: 'main'
          
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          
      - run: |
          docker build . --tag numberone.azurecr.io/numerouno:${{ steps.bump.outputs.version }} --tag numberone.azurecr.io/numerouno:latest
          docker push numberone.azurecr.io/numerouno:${{ steps.bump.outputs.version }}
          docker push numberone.azurecr.io/numerouno:latest
