name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, dev ]
jobs:
  build:
    if: github.event.head_commit.committer.name != 'Versioning Action'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Build'
      run: |
        npm install
        npm run build

    - name: 'Run Tests'
      run: npm run test

    - name: 'Build Image'
      run: docker build .
